[tool.cibuildwheel]
build = "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-* cp314-* cp314t-* cp315-* cp315t*"
build-frontend = "build[uv]"
test-command = "pytest {project}/tests/unit"
test-groups = ["test-unit"]

[tool.cibuildwheel.pyodide]
build = "cp314-*"
# https://cibuildwheel.pypa.io/en/stable/platforms/#pyodide
test-command = "python -m pytest {project}/tests/unit"
